// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalInterviewDayforce.Configs;

#nullable disable

namespace TechnicalInterviewDayforce.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    partial class PayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalInterviewDayforce.Models.PaySummaryRecord", b =>
                {
                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EarningsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RateOfPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPayAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeNumber", "Job", "Dept");

                    b.ToTable("PaySummaries");
                });

            modelBuilder.Entity("TechnicalInterviewDayforce.Models.RateTableRow", b =>
                {
                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveEnd")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Job", "Dept", "EffectiveStart");

                    b.ToTable("RateTable");
                });

            modelBuilder.Entity("TechnicalInterviewDayforce.Models.TimecardRecord", b =>
                {
                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateWorked")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeptWorked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EarningsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobWorked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeNumber", "DateWorked");

                    b.ToTable("Timecards");
                });
#pragma warning restore 612, 618
        }
    }
}
